blank_issues_enabled: true
contact_links:
  - name: TrackMania Exchange Discord
    url: https://discordapp.com/invite/Ttkw54Y
    about: 'Ask questions and discuss the TMX Knockout United event in the #knockouts channel'
  - name: The TMX Admin & Mod Team
    url: https://united.tm-exchange.com/?action=postupdate&id=contactus
    about: Please report user behaviour and inappropriate content by contacting us
